
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  tags: gitlab_runner

- name: Install Docker
  apt:
    name: docker.io
    state: present
  tags: gitlab_runner

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: gitlab_runner

- name: Create GitLab Runner config directory
  file:
    path: /srv/gitlab-runner/config
    state: directory
    mode: "0755"
  tags: gitlab_runner

- name: Start GitLab Runner container
  community.docker.docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart_policy: always
    state: started
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
  tags: gitlab_runner

- name: Install Ansible inside GitLab Runner container
  command: >
    docker exec gitlab-runner bash -lc
    "apt-get update && apt-get install -y ansible sshpass python3"
  tags: gitlab_runner

- name: Register GitLab Runner (nur beim ersten Mal)
  command: >
    docker exec gitlab-runner gitlab-runner register
    --non-interactive
    --url {{ gitlab_url }}
    --token {{ gitlab_runner_token }}
    --executor shell
    --name "gitlab-runner"
  args:
    creates: /srv/gitlab-runner/config/config.toml
  tags: gitlab_runner
